# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='comment',
            field=models.TextField(default=None),
        ),
    ]
