# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='comment',
        ),
    ]
