# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_auto_20190806_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='issue',
        ),
    ]
